[project]
name = "opt_testing"
authors = ["Evan Lang <evan.d.lang@nasa.gov>"]
description = "Add a short description here"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = ">=3.10"
h5py = ">=3.12.1,<4"
xarray = "==2025.1.2"
h5netcdf = ">=1.4.1,<2"
s3fs = "==2025.2.0"
tqdm = "*"
dask = "==2025.2.0"
natsort = ">=8.4.0,<9"
rechunker = ">=0.5.2,<0.6"
matplotlib = "*"
virtualizarr = "==1.3"
fastparquet = "*"
joblib  = "*"
zarr = "==3.0.3"
crc32c = ">=1.7,<=2.7"
kerchunk = "==0.2.8"
fsspec = "==2025.2.0"
ipython = "*"
requests = "*"
bayesian-optimization = "*"

[system-requirements]
linux = "4.12"
libc = "2.22"

[pypi-dependencies]
humanreadable = ">=0.4.0, <0.5"
humanize = ">=4.11.0, <5"


